version: "1.0"

x-defaults: &default
  restart: unless-stopped
# 使用当前目录的 Dockerfile 来构建 docker 镜像
  build: 
    context: ../
    dockerfile: Dockerfile
  volumes:
# 本文件存放于.devcontainer/中，因而此处要把上级目录(源代码目录)挂载到工作目录
# 根据所需情况可以进行修改
    - ..:/home/dev/projects/

services:
  projects-dev-python-v1:
    <<: *default
    container_name: projects-dev-python-v1
    hostname: "python-projects-h1"
# 如果在Dockerfile中修改过用户名，此处也要对应修改用户名和工作目录
    user: dev
    working_dir: /home/dev/projects
# 修改安全配置，以运行gdb server
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
# 开启 ssh 服务，这样 vscode 就能通过 ssh 连接进来了
# 同时通过 tailf 命令保持 container 不要退出的状态
    command:
      bash -c "sudo service ssh restart && tail -f /dev/null"
# 此处将容器的22端口映射到主机的2223上，且仅对本机开放
    ports: 
      - "127.0.0.1:2223:22"